SRCS-$(CONFIG_X86_32) = arch/x86/cpuid.asm arch/x86/spinlock.asm

SRCS-$(CONFIG_X86_64) = arch/x86/cpuid_64.asm arch/x86/spinlock_64.asm

SRCS		+= $(SRCS-y) arch/x86/cpufeature.c arch/x86/portio.c arch/x86/spinlock.asm arch/x86/read_tsc.asm
