SRCS	= strace.c xlat.c syscall.c mem.c util.c print_mode.c stat.c dup.c ioctl.c \
			open.c link.c net.c clone.c wait.c signal.c poll.c eventfd.c time.c epoll.c \
			sockaddr.c io.c dirent.c exec.c umask.c chmod.c getsetid.c msghdr.c fcntl.c \
			access.c utimes.c uid.c

PROG	= strace

INSTALL_PREFIX=/usr/bin

include lyos.prog.mk
