SRCS	= strace.c xlat.c mem.c util.c print_mode.c stat.c dup.c ioctl.c open.c link.c \
			net.c clone.c wait.c signal.c poll.c eventfd.c time.c epoll.c sockaddr.c
PROG	= strace

INSTALL_PREFIX=/usr/bin

include lyos.prog.mk
