#
# Makefile for libpthread.
#

SRCS	= pthread.c pthread_attr.c pthread_create.c pthread_join.c pthread_mutex.c \
			pthread_cond.c pthread_rwlock.c pthread_once.c pthread_specific.c \
			pthread_barrier.c pthread_cleanup.c

LIB		= pthread

include lyos.lib.mk
