#
# Makefile for device manager.

SRCS	= main.c ddmap.c global.c bus.c class.c device.c uevent.c
LIBS	= sysfs memfs fsdriver asyncdriver bdev devman netlink coro lyos

PROG	= devman

include lyos.service.mk
