#
# Makefile for libdrmdriver.
#

SRCS		= driver.c ioctl.c mode_config.c encoder.c connector.c plane.c crtc.c mode_object.c \
				modes.c dumb_buffer.c gem.c framebuffer.c file.c
LIB			= drmdriver

include lyos.lib.mk
