#include "asm.h"

#define UC_FLAGS 0
#define UC_LINK  (UC_FLAGS + REG_SIZE)

#define GREGS_BASE (UC_LINK + REG_SIZE)

#define X1  (GREGS_BASE + 0 * REG_SIZE)
#define X2  (GREGS_BASE + 1 * REG_SIZE)
#define X3  (GREGS_BASE + 2 * REG_SIZE)
#define X4  (GREGS_BASE + 3 * REG_SIZE)
#define X5  (GREGS_BASE + 4 * REG_SIZE)
#define X6  (GREGS_BASE + 5 * REG_SIZE)
#define X7  (GREGS_BASE + 6 * REG_SIZE)
#define X8  (GREGS_BASE + 7 * REG_SIZE)
#define X9  (GREGS_BASE + 8 * REG_SIZE)
#define X10 (GREGS_BASE + 9 * REG_SIZE)
#define X11 (GREGS_BASE + 10 * REG_SIZE)
#define X12 (GREGS_BASE + 11 * REG_SIZE)
#define X13 (GREGS_BASE + 12 * REG_SIZE)
#define X14 (GREGS_BASE + 13 * REG_SIZE)
#define X15 (GREGS_BASE + 14 * REG_SIZE)
#define X16 (GREGS_BASE + 15 * REG_SIZE)
#define X17 (GREGS_BASE + 16 * REG_SIZE)
#define X18 (GREGS_BASE + 17 * REG_SIZE)
#define X19 (GREGS_BASE + 18 * REG_SIZE)
#define X20 (GREGS_BASE + 19 * REG_SIZE)
#define X21 (GREGS_BASE + 20 * REG_SIZE)
#define X22 (GREGS_BASE + 21 * REG_SIZE)
#define X23 (GREGS_BASE + 22 * REG_SIZE)
#define X24 (GREGS_BASE + 23 * REG_SIZE)
#define X25 (GREGS_BASE + 24 * REG_SIZE)
#define X26 (GREGS_BASE + 25 * REG_SIZE)
#define X27 (GREGS_BASE + 26 * REG_SIZE)
#define X28 (GREGS_BASE + 27 * REG_SIZE)
#define X29 (GREGS_BASE + 28 * REG_SIZE)
#define X30 (GREGS_BASE + 29 * REG_SIZE)
#define X31 (GREGS_BASE + 30 * REG_SIZE)
#define PC  (GREGS_BASE + 31 * REG_SIZE)
