#!/bin/sh

echo "Starting system services..."
# service up /sbin/ata
service up /sbin/virtio-blk
service up /sbin/ext2fs
service up /sbin/procfs
service up /sbin/input
service up /sbin/atkbd
service up /sbin/fb
service up /sbin/virtio-gpu

mount -a
