static struct xlat_data epollevents_data[] = {
    XLAT(EPOLLIN),     XLAT(EPOLLPRI),     XLAT(EPOLLOUT),
    XLAT(EPOLLERR),    XLAT(EPOLLHUP),     XLAT(EPOLLRDNORM),
    XLAT(EPOLLRDBAND), XLAT(EPOLLWRNORM),  XLAT(EPOLLWRBAND),
    XLAT(EPOLLMSG),    XLAT(EPOLLRDHUP),   XLAT(EPOLLEXCLUSIVE),
    XLAT(EPOLLWAKEUP), XLAT(EPOLLONESHOT), XLAT(EPOLLET),
};

static DEFINE_XLAT(epollevents);
