static struct xlat_data netlink_protocols_data[] = {
    XLAT(NETLINK_ROUTE),      XLAT(NETLINK_UNUSED),
    XLAT(NETLINK_USERSOCK),   XLAT(NETLINK_FIREWALL),
    XLAT(NETLINK_SOCK_DIAG),  XLAT(NETLINK_NFLOG),
    XLAT(NETLINK_XFRM),       XLAT(NETLINK_SELINUX),
    XLAT(NETLINK_ISCSI),      XLAT(NETLINK_AUDIT),
    XLAT(NETLINK_FIB_LOOKUP), XLAT(NETLINK_CONNECTOR),
    XLAT(NETLINK_NETFILTER),  XLAT(NETLINK_IP6_FW),
    XLAT(NETLINK_DNRTMSG),    XLAT(NETLINK_KOBJECT_UEVENT),
    XLAT(NETLINK_GENERIC),    XLAT(NETLINK_SCSITRANSPORT),
    XLAT(NETLINK_ECRYPTFS),   XLAT(NETLINK_RDMA),
    XLAT(NETLINK_CRYPTO),     XLAT(NETLINK_SMC),
};

static DEFINE_XLAT(netlink_protocols);
